version: '3.8'

services:
  # PHP application for testing
  app:
    build:
      context: .
      dockerfile: Dockerfile.testing
    container_name: cobra-testing-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
    environment:
      - APP_ENV=testing
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=testing
      - DB_USERNAME=testing
      - DB_PASSWORD=testing
    depends_on:
      - mysql
    networks:
      - cobra-testing

  # MySQL database for testing
  mysql:
    image: mysql:8.0
    container_name: cobra-testing-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cobra-testing

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: cobra-testing-redis
    ports:
      - "6380:6379"
    networks:
      - cobra-testing

  # Mailpit for email testing
  mailpit:
    image: axllent/mailpit
    container_name: cobra-testing-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - cobra-testing

volumes:
  mysql_data:

networks:
  cobra-testing:
    driver: bridge
