.eslintrc.js
.github/workflows/comprehensive-tests.yml
.gitlab-ci-backup.yml
.gitlab-ci-old.yml
.gitlab-ci.yml
.stylelintrc.json
deptrac.yaml
docker-compose.testing.yml
docker/docker-compose.scale.yml
docs/CHANGELOG.md
docs/CONTRIBUTING.md
docs/README.md
docs/stats.html
eslint.config.js
infection.json5
phpstan.strict.neon
pint.json
postcss.config.js
public/js/theme-switcher.js
public/sw.js
resources/css/animations/image-effects.css
resources/css/app.scss
resources/css/critical.css
resources/js/animations/image-effects.js
resources/js/state/Store.js
resources/js/utils/ErrorTracker.js
tests/README.md
tsconfig.json
vite.config.js
