name: Laravel CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      APP_KEY: base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare Laravel Environment
        run: |
          mkdir -p storage/framework/{sessions,views,cache}
          mkdir -p bootstrap/cache
          chmod -R 777 storage bootstrap/cache
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
          php artisan config:clear
          php artisan view:clear
          php artisan route:clear

      - name: Run Pint to FIX files
        run: vendor/bin/pint

      - name: Check for code style changes
        id: pint_diff
        run: |
          git diff --exit-code --quiet || echo "PINT_DIFF_FOUND=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Show Pint changes and fail
        if: env.PINT_DIFF_FOUND == 'true'
        run: |
          echo "Pint made the following changes:"
          git diff
          exit 1
