name: Laravel CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo_mysql, tokenizer, xml, gd, zip
          coverage: none # We can enable this later if needed

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Frontend Assets
        run: npm run build

      - name: Create cache directories
        run: |
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p bootstrap/cache

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
        env:
          APP_ENV: testing
          APP_DEBUG: true
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_CONNECTION: sync

      - name: Run Laravel Pint (Code Style)
        run: vendor/bin/pint --test
        env:
          APP_ENV: testing
          CACHE_DRIVER: array
          SESSION_DRIVER: array

      - name: Run PHPStan (Static Analysis)
        run: vendor/bin/phpstan analyse --memory-limit=1G
        env:
          APP_ENV: testing
          CACHE_DRIVER: array
          SESSION_DRIVER: array

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit
        env:
          APP_ENV: testing
          CACHE_DRIVER: array
          SESSION_DRIVER: array
